---
abstract: 'A simplified interface to Remedy ARSystem'
author:
  - 'Greg George <gng@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.78, CPAN::Meta::Converter version 2.130880'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ARS-Simple
no_index:
  directory:
    - t
    - inc
requires:
  ARS: 1.68
  perl: 5.006
version: 0.01
